spring:
  datasource:
    generate-unique-name: false
    name: game
    url: jdbc:h2:mem:game
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

# URL Console - http://localhost:8080/h2-console
# JDBC - jdbc:h2:mem:game
