spring:
  datasource:
    generate-unique-name: false
    name: game
    url: ${DB_URL}  # JDBC - jdbc:h2:mem:game
  jpa:
    database-platform: ${DB_DIALECT}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

# URL Console: http://localhost:8080/h2-console
# Driver Class: org.h2.Driver
# Username: sa  (По умолчанию)
# Password:     (По умолчанию пусто)
